[colors.bright]
black = "#665c54"
blue = "#8ec07c"
cyan = "#a6d189"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fdf4c1"
yellow = "#fb8c2e"

[colors.normal]
black = "#1e1e1e"
blue = "#8ec07c"
cyan = "#a6d189"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#d5c4a1"
yellow = "#fb8c2e"

[colors.primary]
background = "#1e1e1e"
foreground = "#d5c4a1"

[cursor]
style = "Beam"

[font]
size = 12.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 5

[window]
decorations = "none"
dynamic_title = true
opacity = 0.91

[window.padding]
x = 10
y = 10
