[colors.primary]
background = '#121415'
foreground = '#e2e2e4'
 
[colors.cursor]
text = '#e2e2e4'
cursor = '#c1c7cc' 
 
[colors.vi_mode_cursor]
text = '#121415'
cursor = '#a6cce1' 
 
[colors.search.matches]
foreground = '#41484c' 
background = '#dabde3' 
 
[colors.search.focused_match]
foreground = '#41484c' 
background = '#a6cce1' 
 
[colors.footer_bar]
foreground = '#41484c' 
background = '#e2e2e4' 
 
[colors.hints.start]
foreground = '#41484c' 
background = '#bac9d2' 
 
[colors.hints.end]
foreground = '#41484c' 
background = '#bac9d2' 
 
[colors.selection]
text = '#121415'
background = '#a6cce1'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#a6cce1' 
yellow = '#3f6376' 
blue = '#a6cce1' 
magenta = '#dabde3' 
cyan = '#bac9d2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 