[colors.primary]
background = '#151310'
foreground = '#e8e1dd'
 
[colors.cursor]
text = '#e8e1dd'
cursor = '#d2c4b8' 
 
[colors.vi_mode_cursor]
text = '#151310'
cursor = '#e2c19c' 
 
[colors.search.matches]
foreground = '#4e453c' 
background = '#c5caa2' 
 
[colors.search.focused_match]
foreground = '#4e453c' 
background = '#e2c19c' 
 
[colors.footer_bar]
foreground = '#4e453c' 
background = '#e8e1dd' 
 
[colors.hints.start]
foreground = '#4e453c' 
background = '#d6c3b2' 
 
[colors.hints.end]
foreground = '#4e453c' 
background = '#d6c3b2' 
 
[colors.selection]
text = '#151310'
background = '#e2c19c'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#e2c19c' 
yellow = '#735a3c' 
blue = '#e2c19c' 
magenta = '#c5caa2' 
cyan = '#d6c3b2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 