[colors.primary]
background = '#1a110e'
foreground = '#f2ded9'
 
[colors.cursor]
text = '#f2ded9'
cursor = '#dcc1b8' 
 
[colors.vi_mode_cursor]
text = '#1a110e'
cursor = '#ffb59c' 
 
[colors.search.matches]
foreground = '#56423c' 
background = '#c5ce52' 
 
[colors.search.focused_match]
foreground = '#56423c' 
background = '#ffb59c' 
 
[colors.footer_bar]
foreground = '#56423c' 
background = '#f2ded9' 
 
[colors.hints.start]
foreground = '#56423c' 
background = '#f8b8a2' 
 
[colors.hints.end]
foreground = '#56423c' 
background = '#f8b8a2' 
 
[colors.selection]
text = '#1a110e'
background = '#ffb59c'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb59c' 
yellow = '#9d4220' 
blue = '#ffb59c' 
magenta = '#c5ce52' 
cyan = '#f8b8a2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 